# Generated by Django 4.2.7 on 2023-11-29 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pothole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("street_address", models.CharField(max_length=200)),
                ("size", models.IntegerField()),
                ("location", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Reporter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                ("phonenumber", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Workorder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("crew_id", models.IntegerField()),
                ("crew_number_of_people", models.IntegerField()),
                ("equipment", models.CharField(max_length=200)),
                ("repair_hour", models.DecimalField(decimal_places=2, max_digits=5)),
                ("hole_status", models.CharField(max_length=20)),
                ("material", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "cost_of_repair",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "pothole_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="citizen.pothole",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pothole",
            name="reporter_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="citizen.reporter"
            ),
        ),
        migrations.CreateModel(
            name="DamageFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type_of_damage", models.CharField(max_length=50)),
                ("dollar_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "pothole_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="citizen.pothole",
                    ),
                ),
                (
                    "reporter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="citizen.reporter",
                    ),
                ),
            ],
        ),
    ]
